# Generated by Django 4.1.2 on 2022-11-07 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('codesecteur', models.CharField(db_column='codeSecteur', max_length=10, primary_key=True, serialize=False)),
                ('nomsecteur', models.CharField(db_column='nomSecteur', max_length=20)),
            ],
            options={
                'db_table': 'secteur',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('prenom', models.CharField(max_length=20, verbose_name='prenom')),
                ('nom', models.CharField(max_length=20, verbose_name='nom')),
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='matricule')),
                ('codesecteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.secteur')),
            ],
            options={
                'db_table': 'Personnel',
            },
        ),
    ]
