# Generated by Django 4.1.2 on 2022-11-03 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('prenom', models.CharField(max_length=20, verbose_name='prenom')),
                ('nom', models.CharField(max_length=20, verbose_name='nom')),
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='matricule')),
            ],
            options={
                'db_table': 'Personnel',
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('nomSecteur', models.CharField(max_length=50, verbose_name='nomSecteur')),
                ('codeSecteur', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='codeSecteur')),
            ],
            options={
                'db_table': 'Secteur',
            },
        ),
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('matricule', models.OneToOneField(db_column='matricule', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Collaborateur',
            },
        ),
        migrations.CreateModel(
            name='Superuser',
            fields=[
                ('matricule', models.OneToOneField(db_column='matricule', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.BooleanField()),
            ],
            options={
                'db_table': 'Superuser',
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='codeSecteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.secteur'),
        ),
    ]
