# Generated by Django 4.1.2 on 2022-11-07 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('matricule', models.OneToOneField(db_column='matricule', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaborateur',
            },
        ),
        migrations.CreateModel(
            name='Superuser',
            fields=[
                ('matricule', models.OneToOneField(db_column='matricule', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.BooleanField()),
            ],
            options={
                'db_table': 'superuser',
            },
        ),
    ]
