# Generated by Django 4.1.2 on 2022-11-07 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_collaborateur_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('idquizz', models.AutoField(db_column='idQuizz', primary_key=True, serialize=False)),
                ('nomfichier', models.CharField(db_column='nomFichier', max_length=30)),
                ('urlfichier', models.CharField(db_column='urlFichier', max_length=200)),
                ('codesecteur', models.ForeignKey(db_column='codeSecteur', on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.secteur')),
                ('matricule', models.ForeignKey(blank=True, db_column='matricule', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.superuser')),
            ],
            options={
                'db_table': 'quizz',
            },
        ),
    ]
