# Generated by Django 4.1.2 on 2022-11-07 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessionquizz',
            fields=[
                ('idsession', models.AutoField(db_column='idSession', primary_key=True, serialize=False)),
                ('evaluation', models.BooleanField()),
                ('datecreation', models.DateField(db_column='dateCreation')),
                ('dateexpiration', models.DateField(blank=True, db_column='dateExpiration', null=True)),
                ('timer', models.IntegerField(blank=True, null=True)),
                ('idquizz', models.ForeignKey(db_column='idQuizz', on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quizz')),
                ('matricule', models.ForeignKey(db_column='matricule', on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.superuser')),
            ],
            options={
                'db_table': 'sessionQuizz',
            },
        ),
    ]
