# Generated by Django 4.1.2 on 2022-11-07 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_sessionquizz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('idhisto', models.AutoField(db_column='idHisto', primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('dateparticipation', models.DateField(blank=True, db_column='dateParticipation', null=True)),
                ('idsession', models.ForeignKey(db_column='idSession', on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.sessionquizz')),
                ('matricule', models.ForeignKey(db_column='matricule', on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.collaborateur')),
            ],
            options={
                'db_table': 'historique',
            },
        ),
    ]
