# Generated by Django 4.1.2 on 2022-11-07 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_historique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='codesecteur',
            field=models.ForeignKey(db_column='codesecteur', on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.secteur'),
        ),
        migrations.AlterField(
            model_name='secteur',
            name='codesecteur',
            field=models.CharField(db_column='codesecteur', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='secteur',
            name='nomsecteur',
            field=models.CharField(db_column='nomsecteur', max_length=20),
        ),
    ]
