# Generated by Django 4.1.2 on 2022-11-10 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quizz_codesecteur_alter_secteur_codesecteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='codesecteur',
            field=models.ForeignKey(blank=True, db_column='codesecteur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.secteur'),
        ),
    ]
