# Generated by Django 4.1.3 on 2022-11-03 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('codesecteur', models.CharField(db_column='codeSecteur', max_length=10, primary_key=True, serialize=False)),
                ('nomsecteur', models.CharField(db_column='nomSecteur', max_length=20)),
            ],
            options={
                'db_table': 'secteur',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('matricule', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('idlogin', models.CharField(db_column='idLogin', max_length=30)),
                ('mdp', models.CharField(max_length=30)),
                ('codesecteur', models.ForeignKey(db_column='codeSecteur', on_delete=django.db.models.deletion.DO_NOTHING, to='testdb.secteur')),
            ],
            options={
                'db_table': 'personnel',
            },
        ),
    ]
