# Generated by Django 4.1.3 on 2022-11-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='Secteur',
        ),
    ]
