# Generated by Django 4.1.3 on 2022-11-03 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('nomSecteur', models.CharField(max_length=50, verbose_name='nomSecteur')),
                ('codeSecteur', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='codeSecteur')),
            ],
            options={
                'db_table': 'Secteur',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('prenom', models.CharField(max_length=20, verbose_name='prenom')),
                ('nom', models.CharField(max_length=20, verbose_name='nom')),
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='matricule')),
                ('codeSecteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identification.secteur')),
            ],
            options={
                'db_table': 'Personnel',
            },
        ),
    ]
